### ISSUE TITLE
Feedback Max

### ISSUE THREAD

**Issue by MaximilianVomhof** [opensource-construction/model-checker#13]
questions:
- see comments

additions:
- can we add one check in the beginning that indicates the total number of elements that were included and show the distribution on the different types in a graph
- we need to add a document on the front page that frames the process (what is the goal of the tool / what rules are included / which elements are resp. are not included in the checks / ...)

**Comment by MaximilianVomhof** [comment]
checks are doubled?
<img width="1013" alt="Bildschirmfoto 2024-05-27 um 10 29 06" src="https://github.com/opensource-construction/model-checker/assets/126971887/f1718f73-3cda-4492-9957-9f8256f6db69">

**Comment by MaximilianVomhof** [comment]
@ocni-dtu can you add more groups (10 instead of 5 or as many as possible to keep it readable) to this graph?
<img width="1018" alt="image" src="https://github.com/opensource-construction/model-checker/assets/126971887/089ab7a2-0e8d-47c0-9f15-971c1f7284b8">

**Comment by louistrue** [comment]
> checks are doubled? <img alt="Bildschirmfoto 2024-05-27 um 10 29 06" width="1013" src="https://private-user-images.githubusercontent.com/126971887/334026102-f1718f73-3cda-4492-9957-9f8256f6db69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3OTk0MDIsIm5iZiI6MTcxNjc5OTEwMiwicGF0aCI6Ii8xMjY5NzE4ODcvMzM0MDI2MTAyLWYxNzE4ZjczLTNjZGEtNDQ5Mi05OTU3LTlmODI1NmY2ZGI2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QwODM4MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04N2JiMmYxNTIzYjNkNTRiMmY2Mjc4ZTA3YTI2YjAxZTRiZWQ2ZDcxYTNmZjcwZTU3NzljNjhmMGExNjNkNWVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bjzHVA8Qv6u_vHN1T2r1raiL5s-4baCO34n1x_lopLk">

yes, on purpose: 1st one gives Project/site/building names and second one shows relations. We talked about uniting project/site/building relations but ultimately deccided against it because elements might be assigned to building but not project...

**Comment by louistrue** [comment]
> questions:
> 
> * see comments
> 
> additions:
> 
> * can we add one check in the beginning that indicates the total number of elements that were included and show the distribution on the different types in a graph


I think the last checking rule gives that now, but I agree there's room for improvement: 
![image](https://github.com/opensource-construction/model-checker/assets/78563314/1d7a2bc3-bac0-4674-b2d8-b00a4d0afff2)

**Comment by louistrue** [comment]
> @ocni-dtu can you add more groups (10 instead of 5 or as many as possible to keep it readable) to this graph? <img alt="image" width="1018" src="https://private-user-images.githubusercontent.com/126971887/334026826-089ab7a2-0e8d-47c0-9f15-971c1f7284b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NDIzNDYsIm5iZiI6MTcxNjg0MjA0NiwicGF0aCI6Ii8xMjY5NzE4ODcvMzM0MDI2ODI2LTA4OWFiN2EyLTBlOGQtNDdjMC05ZjE1LTk3MWMxZjcyODRiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QyMDM0MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OGYxMDk0MTdmM2EwZTNkYjVhMzMzNGRhNjFlOGMwZGE3YTFmYzM2YmYyN2Y4ZjhkOTM0NTUzNTljNTliM2NkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jgVTTb3HDWqCEUkbrlmam7PuKPn28LORHfHHLd-0pdI">

fixed with #14

**Comment by louistrue** [comment]
@ocni-dtu Maybe can can add these too?

Rule descriptions: 

1. Project Name Validation: Ensures every project has a meaningful and valid name.
2. Project Associations: Verifies that all project-related elements are correctly linked.
3. Site Name Validation: Confirms that site names are properly defined.
4. Site Associations: Checks the proper linkage of site-related elements.
5. Building Name Validation: Ensures buildings within the project have clear and valid names.
6. Building Associations: Validates connections between buildings and other elements.
7. Story Name Validation: Ensures that every story or floor within a building is named correctly.
8. Story Associations: Verifies that elements are appropriately associated with their respective stories.
9. Space Name Validation: Ensures that all spaces are named clearly and accurately.
10. Object Name Validation: Confirms that all objects in the project have valid names.
11. Object Description Validation: Ensures that every object has a proper description.
12. Type Name Validation: Verifies that types are named correctly, avoiding ambiguities.
13. Material Associations: Ensures that all objects have associated material definitions.
14. Predefined Type Check: Confirms that predefined types are specified and valid.
15. Element Validation: Identifies BuildingElementProxies.


1. Projektname-Validierung: Stellt sicher, dass IfcProject.Name einen Namen hat.
2. Projektverbindung: Überprüft, ob alle  Elemente korrekt mit IfcProject verknüpft sind.
3. Standortname-Validierung: Bestätigt, dass IfcSite.Name definiert ist.
4. Standortverbindungen: Prüft die ordnungsgemässe Verknüpfung von Entitäten und IfcSite.
5. Gebäudename-Validierung: Stellt sicher, dass IfcBuilding einen Namen hat.
6. Gebäudeverbindungen: Validiert Verbindungen zwischen IfcBuilding und  Entitäten.
7. Geschossname-Validierung: Stellt sicher, dass jede Etage oder jeder Stockwerk korrekt benannt ist.
8. Geschosszuordnung: Überprüft, ob Elemente richtig mit ihren jeweiligen Geschossen verknüpft sind.
9. Raumname-Validierung: Stellt sicher, dass alle Räume klar und genau benannt sind.
10. Name-Validierung: Bestätigt, dass alle Objekte im Projekt gültige Namen haben.
11. Description-Validierung: Stellt sicher, dass jedes Objekt eine ordnungsgemässe Beschreibung hat.
12. Typname-Validierung: Überprüft, ob Typen korrekt benannt sind, um Unklarheiten zu vermeiden.
13. Materialzuweisungen: Stellt sicher, dass alle Objekte zugewiesene Materialdefinitionen haben.
14. Prede Type Check: Bestätigt, dass vordefinierte Typen gültig sind (keine UNDEFINED).
15. Elementvalidierung: Identifiziert BuildingElementProxies.

**Comment by ocni-dtu** [comment]
> @ocni-dtu Maybe can can add these too?
> 
> Rule descriptions:
> 
>     1. Project Name Validation: Ensures every project has a meaningful and valid name.
> 
>     2. Project Associations: Verifies that all project-related elements are correctly linked.
> 
>     3. Site Name Validation: Confirms that site names are properly defined.
> 
>     4. Site Associations: Checks the proper linkage of site-related elements.
> 
>     5. Building Name Validation: Ensures buildings within the project have clear and valid names.
> 
>     6. Building Associations: Validates connections between buildings and other elements.
> 
>     7. Story Name Validation: Ensures that every story or floor within a building is named correctly.
> 
>     8. Story Associations: Verifies that elements are appropriately associated with their respective stories.
> 
>     9. Space Name Validation: Ensures that all spaces are named clearly and accurately.
> 
>     10. Object Name Validation: Confirms that all objects in the project have valid names.
> 
>     11. Object Description Validation: Ensures that every object has a proper description.
> 
>     12. Type Name Validation: Verifies that types are named correctly, avoiding ambiguities.
> 
>     13. Material Associations: Ensures that all objects have associated material definitions.
> 
>     14. Predefined Type Check: Confirms that predefined types are valid (not UNDEFINED).
> 
>     15. Element Validation: Identifies BuildingElementProxies.
> 
> 
> German:
> 
>     1. Projektname-Validierung: Stellt sicher, dass IfcProject.Name einen Namen hat.
> 
>     2. Projektverbindung: Überprüft, ob alle  Elemente korrekt mit IfcProject verknüpft sind.
> 
>     3. Standortname-Validierung: Bestätigt, dass IfcSite.Name definiert ist.
> 
>     4. Standortverbindungen: Prüft die ordnungsgemässe Verknüpfung von Entitäten und IfcSite.
> 
>     5. Gebäudename-Validierung: Stellt sicher, dass IfcBuilding einen Namen hat.
> 
>     6. Gebäudeverbindungen: Validiert Verbindungen zwischen IfcBuilding und  Entitäten.
> 
>     7. Geschossname-Validierung: Stellt sicher, dass jede Etage oder jeder Stockwerk korrekt benannt ist.
> 
>     8. Geschosszuordnung: Überprüft, ob Elemente richtig mit ihren jeweiligen Geschossen verknüpft sind.
> 
>     9. Raumname-Validierung: Stellt sicher, dass alle Räume klar und genau benannt sind.
> 
>     10. Name-Validierung: Bestätigt, dass alle Objekte im Projekt gültige Namen haben.
> 
>     11. Description-Validierung: Stellt sicher, dass jedes Objekt eine ordnungsgemässe Beschreibung hat.
> 
>     12. Typname-Validierung: Überprüft, ob Typen korrekt benannt sind, um Unklarheiten zu vermeiden.
> 
>     13. Materialzuweisungen: Stellt sicher, dass alle Objekte zugewiesene Materialdefinitionen haben.
> 
>     14. Predefined Types Check: Bestätigt, dass vordefinierte Typen gültig sind (keine UNDEFINED).
> 
>     15. Elementvalidierung: Identifiziert BuildingElementProxies.

@louistrue, where do you want these?

**Comment by louistrue** [comment]
> @louistrue, where do you want these?

dont know, maybe add "Rule Descriptions" below upload card as expandable so it doesnt clutter upload ui?

 there we could also add a general description like 

> IFC Model Checker points to commonly found issues in .ifc files, leading to high quality data in the AEC industry. Checking your uploaded IFC files happens fully clientside, we don't save any data - nothing leaves your device and everything is deleted after session gets closed.

**Comment by ocni-dtu** [comment]
Added an info modal in the latest updated
@MaximilianVomhof @louistrue
