### ISSUE TITLE
Add Timestamp and Author

### ISSUE THREAD

**Issue by MatPro47** [opensource-construction/model-checker#21]
Would it be possible to add the Author and the Time Stamp of the Model to the Name of the Model in the titel above?
<img width="1288" alt="Bildschirmfoto 2024-06-03 um 13 29 13" src="https://github.com/opensource-construction/model-checker/assets/171570170/00622fbf-829e-4938-a016-c58b4639731d">
<img width="572" alt="Model Info" src="https://github.com/opensource-construction/model-checker/assets/171570170/e9631196-294c-44e8-903b-653418dacbf9">

**Comment by louistrue** [comment]
Yes 👍
