### ISSUE TITLE
Issue with Type Name / Material Name / Predefined Type

### ISSUE THREAD

**Issue by MatPro47** [opensource-construction/model-checker#32]
I group several issues in one here:

1. No dropdown possibility for Predefined Type and Material Name list
2. The Ifc Type / Type Name Rule shows 100% success, but only 24 objects, there has to be something wrong as I have more than 4'000 objects from one type as an example
3. The Description Rule shows 6% succeed, but my model has no Ifc Description filled out
4. The List below BuildingElementProxy doesn't show BuildingElementProxy Elements. It should been the list with the BuildingElementProxy Elements sorted by their Name.
5. Also the Author is not displayed...

<img width="401" alt="Bildschirmfoto 2024-06-11 um 14 25 04" src="https://github.com/opensource-construction/model-checker/assets/171570170/4152bf4b-6a1a-4d40-90ea-89f36586b407">
<img width="422" alt="Bildschirmfoto 2024-06-11 um 14 26 00" src="https://github.com/opensource-construction/model-checker/assets/171570170/358fc640-c835-419f-98bb-03c4aed07263">
<img width="426" alt="Bildschirmfoto 2024-06-11 um 14 29 00" src="https://github.com/opensource-construction/model-checker/assets/171570170/8f7712ee-add9-4a75-b5ce-60edf2872bbc">

**Comment by MatPro47** [comment]
https://www.swisstransfer.com/d/1f60cd5f-f07e-4371-8cfd-81579d1464ba

**Comment by louistrue** [comment]
Thanks, am looking into the first 2 points. Didnt't happen with sample files 😅

Regarding 3.: 
I do find Descriptions in the file that show up correctly: 
![image](https://github.com/opensource-construction/model-checker/assets/78563314/5b620208-a970-4a6d-86ae-8e1af7c86722)

and 4.: we discussed this question yesterday and thought it might be helpful to get an overview of what ifc classes are used in file. We can switch 👍

**Comment by MatPro47** [comment]
Hey @louistrue thanks for the fast Feedback and sorry for the one with the Description. My Filter was wrong!
If you could switch for the Proxys, because my intention is to validate if the proxies that are utilized are indeed a reason to use a proxy and you can find this out with the name.

**Comment by louistrue** [comment]
No worries @MatPro47, I apreciate the feedback from actual users 👍 I found and fixed all errors and will be releasing the updated version soon. Even made some more enhancements while I was at it 😊
